import React from 'react';
import { useStore } from '../../context/StoreContext';
import { MessageCircle, Phone, MapPin, User, CheckCircle2, Clock } from 'lucide-react';

export const OrdersManager = () => {
  const { orders, settings } = useStore();
  const currency = settings.currency || "$";

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900">
            WhatsApp Order Receipts & Dispatches
          </h2>
          <p className="text-xs text-slate-500 mt-0.5 font-medium">
            Log of customer orders dispatched via direct CueMart WhatsApp link.
          </p>
        </div>

        <div className="px-3.5 py-1.5 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-200 text-xs font-bold inline-flex items-center gap-2 self-start sm:self-auto">
          <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
          <span>{orders.length} Logged Dispatches</span>
        </div>
      </div>

      {orders.length === 0 ? (
        <div className="p-12 text-center bg-white rounded-2xl border border-slate-100 space-y-3">
          <div className="w-12 h-12 rounded-full bg-slate-100 text-slate-400 flex items-center justify-center mx-auto">
            <MessageCircle className="w-6 h-6 text-orange-600" />
          </div>
          <h3 className="font-bold text-slate-800 text-base">No orders recorded yet</h3>
          <p className="text-xs text-slate-500 max-w-sm mx-auto">
            Orders generated by storefront shoppers during WhatsApp checkout will automatically be logged here.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {orders.map((order) => (
            <div 
              key={order.id}
              className="bg-white rounded-2xl border border-slate-100 p-5 shadow-xs hover:shadow-md transition-shadow flex flex-col justify-between space-y-4"
            >
              <div className="space-y-3">
                {/* Order ID & Status */}
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-bold text-orange-800 bg-orange-50 px-2.5 py-1 rounded-lg border border-orange-200">
                    {order.id}
                  </span>
                  <span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-200">
                    <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                    <span>{order.status}</span>
                  </span>
                </div>

                {/* Customer Details */}
                <div className="space-y-1 text-xs text-slate-700">
                  <div className="flex items-center gap-2 font-bold text-slate-900 text-sm">
                    <User className="w-4 h-4 text-slate-400" />
                    <span>{order.customerName}</span>
                  </div>
                  <div className="flex items-center gap-2 text-slate-500 font-medium">
                    <Phone className="w-3.5 h-3.5 text-slate-400" />
                    <span>{order.customerPhone}</span>
                  </div>
                  <div className="flex items-start gap-2 text-slate-500 font-medium">
                    <MapPin className="w-3.5 h-3.5 text-slate-400 shrink-0 mt-0.5" />
                    <span>{order.address}</span>
                  </div>
                </div>

                {/* Items List */}
                <div className="pt-3 border-t border-slate-100 space-y-2">
                  <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                    Ordered Items
                  </div>
                  <ul className="space-y-1.5 text-xs">
                    {order.items.map((item, idx) => (
                      <li key={idx} className="flex justify-between items-center bg-slate-50 p-2 rounded-lg">
                        <div>
                          <span className="font-bold text-slate-800">{item.name}</span>
                          <span className="text-[10px] text-slate-500 ml-1.5">({item.size} / {item.color})</span>
                        </div>
                        <span className="font-extrabold text-slate-900">
                          {item.quantity} × {currency}{item.price}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Order Footer: Total & Date */}
              <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-xs">
                <div className="flex items-center gap-1.5 text-slate-400 text-[11px] font-medium">
                  <Clock className="w-3.5 h-3.5" />
                  <span>{new Date(order.date).toLocaleDateString()} at {new Date(order.date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                </div>
                <div className="text-right">
                  <span className="text-[10px] uppercase font-bold text-slate-400 block">Total Paid</span>
                  <span className="font-extrabold text-base text-slate-900">{currency}{Number(order.total).toLocaleString()}</span>
                </div>
              </div>

            </div>
          ))}
        </div>
      )}
    </div>
  );
};
